<?php
namespace App\Http\Controllers\Api;

use App\Domain\Runtime\RuntimeActionService;
use App\Enums\RuntimeActionStatus;
use App\Enums\RuntimeActionType;
use App\Http\Controllers\Controller;
use App\Models\{Aivva,AivvaMeetupRequest,AivvaRuntimeAction,AivvaRuntimeLocation};
use Illuminate\Http\{JsonResponse,Request};
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\StreamedResponse;

class RuntimeActionController extends Controller
{
    public function __construct(private readonly RuntimeActionService $actions) {}
    public function health(Request $r):JsonResponse{abort_unless(config('aivva.runtime.enabled'),503,'AIVVA runtime is disabled.');abort_unless($r->user()?->tokenCan('aivva:runtime'),403,'Runtime scope required.');DB::select('select 1');return response()->json(['ok'=>true,'runtime'=>'enabled','authentication'=>'scoped-token','eventStreamSeconds'=>(int)config('aivva.runtime.event_stream_seconds',25),'serverTime'=>now()->toIso8601String()]);}
    public function active(Request $r,Aivva $aivva):JsonResponse{$this->authorizeRuntime($r,$aivva);return response()->json(['data'=>$this->serialize($this->actions->active($aivva))]);}
    public function startDemo(Request $r,Aivva $aivva):JsonResponse{$this->authorizeRuntime($r,$aivva);return response()->json(['data'=>$this->serialize($this->actions->startPlazaDemo($aivva))],201);}
    // FACE_TARGET/INTERACT were opened up to human requesters once
    // RuntimeActionService::validatePayload started enforcing meetup
    // consent (Phase 5B) -- before that fix, allowing a human to request
    // them here would have meant anyone could INTERACT with any AIVVA on
    // the platform with zero authorization, so this list intentionally
    // stayed MOVE_TO/SAY-only until the consent gate existed.
    public function request(Request $r,Aivva $aivva):JsonResponse{$this->authorizeRuntime($r,$aivva);$d=$r->validate(['type'=>['required','in:MOVE_TO,SAY,FACE_TARGET,INTERACT'],'payload'=>['required','array']]);abort_if($this->actions->active($aivva),409,'Finish or cancel the active action first.');$action=$this->actions->create($aivva,RuntimeActionType::from($d['type']),$d['payload'],'HUMAN');return response()->json(['data'=>$this->serialize($action)],201);}
    public function requestMeetup(Request $r,Aivva $aivva):JsonResponse{$this->authorizeRuntime($r,$aivva);$d=$r->validate(['targetAivvaId'=>['required','uuid','exists:aivvas,id'],'locationId'=>['required','string','max:191']]);$target=Aivva::query()->findOrFail($d['targetAivvaId']);abort_if($target->id===$aivva->id||$target->owner_id===$aivva->owner_id||$target->is_platform,422,'Invalid meetup target.');abort_unless(AivvaRuntimeLocation::query()->whereKey($d['locationId'])->where('enabled',true)->exists(),422,'Invalid meetup location.');$existing=AivvaMeetupRequest::query()->where('from_aivva_id',$aivva->id)->where('to_aivva_id',$target->id)->where('proposed_location_id',$d['locationId'])->where('status',AivvaMeetupRequest::PENDING)->where('expires_at','>',now())->first();if($existing)return response()->json(['data'=>$this->meetup($existing),'idempotent'=>true]);$meetup=AivvaMeetupRequest::query()->create(['from_aivva_id'=>$aivva->id,'to_aivva_id'=>$target->id,'proposed_location_id'=>$d['locationId'],'status'=>AivvaMeetupRequest::PENDING,'expires_at'=>now()->addMinutes(15)]);return response()->json(['data'=>$this->meetup($meetup)],201);}
    public function incomingMeetups(Request $r,Aivva $aivva):JsonResponse{$this->authorizeRuntime($r,$aivva);$this->expireMeetups($aivva);return response()->json(['data'=>AivvaMeetupRequest::query()->where('to_aivva_id',$aivva->id)->latest()->get()->map(fn($m)=>$this->meetup($m))->values()]);}
    public function outgoingMeetups(Request $r,Aivva $aivva):JsonResponse{$this->authorizeRuntime($r,$aivva);$this->expireMeetups($aivva);return response()->json(['data'=>AivvaMeetupRequest::query()->where('from_aivva_id',$aivva->id)->latest()->get()->map(fn($m)=>$this->meetup($m))->values()]);}
    public function respondMeetup(Request $r,Aivva $aivva,AivvaMeetupRequest $meetup):JsonResponse{$this->authorizeRuntime($r,$aivva);abort_unless($meetup->to_aivva_id===$aivva->id,403);$d=$r->validate(['response'=>['required','in:ACCEPT,DECLINE']]);$this->expireMeetups($aivva);abort_unless($meetup->status===AivvaMeetupRequest::PENDING,409,'Meetup request is no longer pending.');$meetup->forceFill(['status'=>$d['response']==='ACCEPT'?AivvaMeetupRequest::ACCEPTED:AivvaMeetupRequest::DECLINED,'responded_at'=>now()])->save();return response()->json(['data'=>$this->meetup($meetup)]);}
    public function cancelMeetup(Request $r,Aivva $aivva,AivvaMeetupRequest $meetup):JsonResponse{$this->authorizeRuntime($r,$aivva);abort_unless($meetup->from_aivva_id===$aivva->id,403);abort_unless($meetup->status===AivvaMeetupRequest::PENDING,409);$meetup->forceFill(['status'=>AivvaMeetupRequest::CANCELLED,'responded_at'=>now()])->save();return response()->json(['data'=>$this->meetup($meetup)]);}
    public function trace(Request $r,Aivva $aivva,AivvaRuntimeAction $runtimeAction):JsonResponse{$this->authorizeAction($r,$aivva,$runtimeAction);return response()->json(['data'=>$this->serialize($runtimeAction->fresh())]);}
    public function claim(Request $r,Aivva $aivva,AivvaRuntimeAction $runtimeAction):JsonResponse{$this->authorizeAction($r,$aivva,$runtimeAction);$d=$r->validate(['executionId'=>['required','string','max:100'],'clientInstanceId'=>['required','string','max:100']]);return response()->json(['data'=>$this->serialize($this->actions->claim($runtimeAction,$d['executionId'],$d['clientInstanceId']))]);}
    public function status(Request $r,Aivva $aivva,AivvaRuntimeAction $runtimeAction):JsonResponse{$this->authorizeAction($r,$aivva,$runtimeAction);$d=$r->validate(['executionId'=>['required','string','max:100'],'status'=>['required','in:COMPLETED,FAILED,CANCELLED'],'failureCode'=>['nullable','string','max:80'],'result'=>['nullable','array']]);return response()->json(['data'=>$this->serialize($this->actions->acknowledge($runtimeAction,$d['executionId'],RuntimeActionStatus::from($d['status']),$d['result']??[],$d['failureCode']??null))]);}
    public function cancel(Request $r,Aivva $aivva,AivvaRuntimeAction $runtimeAction):JsonResponse{$this->authorizeAction($r,$aivva,$runtimeAction);return response()->json(['data'=>$this->serialize($this->actions->cancel($runtimeAction))]);}
    public function events(Request $r,Aivva $aivva):StreamedResponse{$this->authorizeRuntime($r,$aivva);$lastVersion=max(0,(int)$r->query('afterVersion',0));$lastActionId=(string)$r->query('afterActionId','');return response()->stream(function()use($aivva,$lastVersion,$lastActionId){$deadline=microtime(true)+(int)config('aivva.runtime.event_stream_seconds',25);$seenVersion=$lastVersion;$seenId=$lastActionId;echo "retry: 1500\n\n";while(microtime(true)<$deadline&&!connection_aborted()){$action=AivvaRuntimeAction::query()->where('aivva_id',$aivva->id)->latest('updated_at')->first();if($action&&($action->id!==$seenId||(int)$action->version>$seenVersion)){$seenId=$action->id;$seenVersion=(int)$action->version;$event=match($action->status){RuntimeActionStatus::Requested=>'AIVVA_ACTION_REQUESTED',RuntimeActionStatus::Cancelled=>'AIVVA_ACTION_CANCELLED',RuntimeActionStatus::Expired=>'AIVVA_ACTION_EXPIRED',default=>'AIVVA_ACTION_UPDATED'};echo 'event: '.$event."\n".'data: '.json_encode($this->serialize($action),JSON_UNESCAPED_SLASHES)."\n\n";}else{echo ": heartbeat\n\n";}if(ob_get_level()>0)@ob_flush();flush();usleep(750000);}},200,['Content-Type'=>'text/event-stream','Cache-Control'=>'no-cache, no-store, private','X-Accel-Buffering'=>'no']);}
    private function authorizeRuntime(Request $r,Aivva $a):void{abort_unless(config('aivva.runtime.enabled'),503);abort_unless($r->user()?->tokenCan('aivva:runtime'),403);abort_unless($a->owner_id===$r->user()?->id,403);}
    private function authorizeAction(Request $r,Aivva $a,AivvaRuntimeAction $x):void{$this->authorizeRuntime($r,$a);abort_unless($x->aivva_id===$a->id,404);}
    private function expireMeetups(Aivva $a):void{AivvaMeetupRequest::query()->where(fn($q)=>$q->where('from_aivva_id',$a->id)->orWhere('to_aivva_id',$a->id))->where('status',AivvaMeetupRequest::PENDING)->where('expires_at','<=',now())->update(['status'=>AivvaMeetupRequest::EXPIRED]);}
    private function meetup(AivvaMeetupRequest $m):array{return ['id'=>$m->id,'fromAivvaId'=>$m->from_aivva_id,'toAivvaId'=>$m->to_aivva_id,'locationId'=>$m->proposed_location_id,'status'=>$m->status,'expiresAt'=>$m->expires_at->toIso8601String(),'respondedAt'=>$m->responded_at?->toIso8601String()];}
    private function serialize(?AivvaRuntimeAction $a):?array{if(!$a)return null;return ['actionId'=>$a->id,'aivvaId'=>$a->aivva_id,'type'=>$a->type->value,'payload'=>$a->payload,'status'=>$a->status->value,'createdAt'=>$a->created_at?->toIso8601String(),'claimedAt'=>$a->claimed_at?->toIso8601String(),'startedAt'=>$a->started_at?->toIso8601String(),'completedAt'=>$a->completed_at?->toIso8601String(),'failureCode'=>$a->failure_code,'correlationId'=>$a->correlation_id,'executionId'=>$a->execution_id,'leaseExpiresAt'=>$a->lease_expires_at?->toIso8601String(),'expiresAt'=>$a->expires_at?->toIso8601String(),'version'=>$a->version];}
}
